services:
  mi-proyecto-devops:
    image: localhost:8082/mi-proyecto-devops
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AMBIENTE=development
      - API_KEY=/run/secrets/api-key2
    secrets:
      - api-key2
secrets:
  api-key2:
    file: api_key2.txt
